// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO users (
    email,
    password_hash,
    name
)
VALUES (
    $1, $2, $3
)
RETURNING id, email, email_verified, password_hash, name, given_name, family_name, picture, preferred_username, is_active, created_at, updated_at, is_platform_admin
`

type CreateAdminParams struct {
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	Name         string `db:"name" json:"name"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createAdmin, arg.Email, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Name,
		&i.GivenName,
		&i.FamilyName,
		&i.Picture,
		&i.PreferredUsername,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPlatformAdmin,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified, password_hash, name, given_name, family_name, picture, preferred_username, is_active, created_at, updated_at, is_platform_admin FROM users 
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Name,
		&i.GivenName,
		&i.FamilyName,
		&i.Picture,
		&i.PreferredUsername,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPlatformAdmin,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified, password_hash, name, given_name, family_name, picture, preferred_username, is_active, created_at, updated_at, is_platform_admin FROM users 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Name,
		&i.GivenName,
		&i.FamilyName,
		&i.Picture,
		&i.PreferredUsername,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPlatformAdmin,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, email_verified, is_active, is_platform_admin, created_at
FROM users
WHERE ($1 = '' OR email ILIKE $2 OR name ILIKE $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListUsersParams struct {
	Column1 interface{} `db:"column_1" json:"column_1"`
	Email   string      `db:"email" json:"email"`
	Limit   int32       `db:"limit" json:"limit"`
}

type ListUsersRow struct {
	ID              uuid.UUID `db:"id" json:"id"`
	Email           string    `db:"email" json:"email"`
	Name            string    `db:"name" json:"name"`
	EmailVerified   bool      `db:"email_verified" json:"email_verified"`
	IsActive        bool      `db:"is_active" json:"is_active"`
	IsPlatformAdmin bool      `db:"is_platform_admin" json:"is_platform_admin"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Column1, arg.Email, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.EmailVerified,
			&i.IsActive,
			&i.IsPlatformAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET is_active = $2, updated_at = NOW() WHERE id = $1
`

type SetUserActiveParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	IsActive bool      `db:"is_active" json:"is_active"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.ExecContext(ctx, setUserActive, arg.ID, arg.IsActive)
	return err
}
