// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_events (
    user_id, org_id, event_type, details, ip_address, user_agent
)
VALUES (
    $1, $2, $3, NULLIF(CAST($4 AS text), '')::jsonb, $5, $6
)
RETURNING id, user_id, org_id, event_type, details, ip_address, user_agent, created_at
`

type InsertAuditEventParams struct {
	UserID    uuid.NullUUID  `db:"user_id" json:"user_id"`
	OrgID     uuid.NullUUID  `db:"org_id" json:"org_id"`
	EventType string         `db:"event_type" json:"event_type"`
	Column4   string         `db:"column_4" json:"column_4"`
	IpAddress pqtype.Inet    `db:"ip_address" json:"ip_address"`
	UserAgent sql.NullString `db:"user_agent" json:"user_agent"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRowContext(ctx, insertAuditEvent,
		arg.UserID,
		arg.OrgID,
		arg.EventType,
		arg.Column4,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.EventType,
		&i.Details,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT e.id, COALESCE(u.name, '') AS user_name, COALESCE(o.name, '') AS org_name, e.event_type, e.details, e.created_at
FROM audit_events e
LEFT JOIN users u ON u.id = e.user_id
LEFT JOIN organizations o ON o.id = e.org_id
WHERE ($1 = '' OR e.org_id::text = $1)
ORDER BY e.created_at DESC
LIMIT $2
`

type ListAuditEventsParams struct {
	Column1 interface{} `db:"column_1" json:"column_1"`
	Limit   int32       `db:"limit" json:"limit"`
}

type ListAuditEventsRow struct {
	ID        uuid.UUID             `db:"id" json:"id"`
	UserName  string                `db:"user_name" json:"user_name"`
	OrgName   string                `db:"org_name" json:"org_name"`
	EventType string                `db:"event_type" json:"event_type"`
	Details   pqtype.NullRawMessage `db:"details" json:"details"`
	CreatedAt time.Time             `db:"created_at" json:"created_at"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEventsRow{}
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.OrgName,
			&i.EventType,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
