// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO oauth_clients (
    client_id, client_secret, name, redirect_uris, base_url
)
VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, client_id, client_secret, base_url, name, redirect_uris, grant_types, response_types, is_active, created_at, updated_at
`

type CreateOAuthClientParams struct {
	ClientID     string   `db:"client_id" json:"client_id"`
	ClientSecret string   `db:"client_secret" json:"client_secret"`
	Name         string   `db:"name" json:"name"`
	RedirectUris []string `db:"redirect_uris" json:"redirect_uris"`
	BaseUrl      string   `db:"base_url" json:"base_url"`
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRowContext(ctx, createOAuthClient,
		arg.ClientID,
		arg.ClientSecret,
		arg.Name,
		pq.Array(arg.RedirectUris),
		arg.BaseUrl,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.BaseUrl,
		&i.Name,
		pq.Array(&i.RedirectUris),
		pq.Array(&i.GrantTypes),
		pq.Array(&i.ResponseTypes),
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveClientByClientID = `-- name: GetActiveClientByClientID :one
SELECT id, client_id, client_secret, base_url, name, redirect_uris, grant_types, response_types, is_active, created_at, updated_at FROM oauth_clients 
WHERE client_id = $1 LIMIT 1
`

func (q *Queries) GetActiveClientByClientID(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRowContext(ctx, getActiveClientByClientID, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.BaseUrl,
		&i.Name,
		pq.Array(&i.RedirectUris),
		pq.Array(&i.GrantTypes),
		pq.Array(&i.ResponseTypes),
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, client_id, client_secret, base_url, name, redirect_uris, grant_types, response_types, is_active, created_at, updated_at FROM oauth_clients 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (OauthClient, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, id)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.BaseUrl,
		&i.Name,
		pq.Array(&i.RedirectUris),
		pq.Array(&i.GrantTypes),
		pq.Array(&i.ResponseTypes),
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOAuthClients = `-- name: ListOAuthClients :many
SELECT id, client_id, client_secret, base_url, name, redirect_uris, grant_types, response_types, is_active, created_at, updated_at FROM oauth_clients
WHERE ($1 = '' OR name ILIKE $2 OR client_id ILIKE $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListOAuthClientsParams struct {
	Column1 interface{} `db:"column_1" json:"column_1"`
	Name    string      `db:"name" json:"name"`
	Limit   int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListOAuthClients(ctx context.Context, arg ListOAuthClientsParams) ([]OauthClient, error) {
	rows, err := q.db.QueryContext(ctx, listOAuthClients, arg.Column1, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthClient{}
	for rows.Next() {
		var i OauthClient
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientSecret,
			&i.BaseUrl,
			&i.Name,
			pq.Array(&i.RedirectUris),
			pq.Array(&i.GrantTypes),
			pq.Array(&i.ResponseTypes),
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateOAuthClientSecret = `-- name: RotateOAuthClientSecret :exec
UPDATE oauth_clients SET client_secret = $2, updated_at = NOW() WHERE id = $1
`

type RotateOAuthClientSecretParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	ClientSecret string    `db:"client_secret" json:"client_secret"`
}

func (q *Queries) RotateOAuthClientSecret(ctx context.Context, arg RotateOAuthClientSecretParams) error {
	_, err := q.db.ExecContext(ctx, rotateOAuthClientSecret, arg.ID, arg.ClientSecret)
	return err
}

const updateOAuthClient = `-- name: UpdateOAuthClient :exec
UPDATE oauth_clients
SET name = $2, redirect_uris = $3, is_active = $4, base_url = $5, updated_at = NOW()
WHERE id = $1
`

type UpdateOAuthClientParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	RedirectUris []string  `db:"redirect_uris" json:"redirect_uris"`
	IsActive     bool      `db:"is_active" json:"is_active"`
	BaseUrl      string    `db:"base_url" json:"base_url"`
}

func (q *Queries) UpdateOAuthClient(ctx context.Context, arg UpdateOAuthClientParams) error {
	_, err := q.db.ExecContext(ctx, updateOAuthClient,
		arg.ID,
		arg.Name,
		pq.Array(arg.RedirectUris),
		arg.IsActive,
		arg.BaseUrl,
	)
	return err
}
