// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entitlement.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteEntitlements = `-- name: DeleteEntitlements :exec
DELETE FROM org_entitlements WHERE org_id = $1
`

func (q *Queries) DeleteEntitlements(ctx context.Context, orgID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEntitlements, orgID)
	return err
}

const listEntitlements = `-- name: ListEntitlements :many
SELECT entitlement
FROM org_entitlements
WHERE org_id = $1
ORDER BY entitlement
`

func (q *Queries) ListEntitlements(ctx context.Context, orgID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listEntitlements, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var entitlement string
		if err := rows.Scan(&entitlement); err != nil {
			return nil, err
		}
		items = append(items, entitlement)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEntitlement = `-- name: UpsertEntitlement :exec
INSERT INTO org_entitlements (org_id, entitlement) VALUES ($1, $2)
ON CONFLICT (org_id, entitlement) DO NOTHING
`

type UpsertEntitlementParams struct {
	OrgID       uuid.UUID `db:"org_id" json:"org_id"`
	Entitlement string    `db:"entitlement" json:"entitlement"`
}

func (q *Queries) UpsertEntitlement(ctx context.Context, arg UpsertEntitlementParams) error {
	_, err := q.db.ExecContext(ctx, upsertEntitlement, arg.OrgID, arg.Entitlement)
	return err
}
