// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countMembersWithRole = `-- name: CountMembersWithRole :one
SELECT COUNT(*) FROM members_accounts WHERE org_id = $1 AND role = $2
`

type CountMembersWithRoleParams struct {
	OrgID uuid.UUID `db:"org_id" json:"org_id"`
	Role  string    `db:"role" json:"role"`
}

func (q *Queries) CountMembersWithRole(ctx context.Context, arg CountMembersWithRoleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMembersWithRole, arg.OrgID, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members_accounts (
    org_id, role, email, password_hash, name, given_name, family_name, picture, preferred_username, is_active
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, org_id, role, email, email_verified, password_hash, name, given_name, family_name, picture, preferred_username, is_active, created_at, updated_at, supervisor_id
`

type CreateMemberParams struct {
	OrgID             uuid.UUID      `db:"org_id" json:"org_id"`
	Role              string         `db:"role" json:"role"`
	Email             string         `db:"email" json:"email"`
	PasswordHash      string         `db:"password_hash" json:"password_hash"`
	Name              string         `db:"name" json:"name"`
	GivenName         sql.NullString `db:"given_name" json:"given_name"`
	FamilyName        sql.NullString `db:"family_name" json:"family_name"`
	Picture           sql.NullString `db:"picture" json:"picture"`
	PreferredUsername sql.NullString `db:"preferred_username" json:"preferred_username"`
	IsActive          bool           `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (MembersAccount, error) {
	row := q.db.QueryRowContext(ctx, createMember,
		arg.OrgID,
		arg.Role,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.GivenName,
		arg.FamilyName,
		arg.Picture,
		arg.PreferredUsername,
		arg.IsActive,
	)
	var i MembersAccount
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Role,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Name,
		&i.GivenName,
		&i.FamilyName,
		&i.Picture,
		&i.PreferredUsername,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SupervisorID,
	)
	return i, err
}

const getMemberByEmail = `-- name: GetMemberByEmail :one
SELECT id, org_id, role, email, email_verified, password_hash, name, given_name, family_name, picture, preferred_username, is_active, created_at, updated_at, supervisor_id FROM members_accounts 
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetMemberByEmail(ctx context.Context, email string) (MembersAccount, error) {
	row := q.db.QueryRowContext(ctx, getMemberByEmail, email)
	var i MembersAccount
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Role,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Name,
		&i.GivenName,
		&i.FamilyName,
		&i.Picture,
		&i.PreferredUsername,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SupervisorID,
	)
	return i, err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, org_id, role, email, email_verified, password_hash, name, given_name, family_name, picture, preferred_username, is_active, created_at, updated_at, supervisor_id FROM members_accounts 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMemberByID(ctx context.Context, id uuid.UUID) (MembersAccount, error) {
	row := q.db.QueryRowContext(ctx, getMemberByID, id)
	var i MembersAccount
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Role,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Name,
		&i.GivenName,
		&i.FamilyName,
		&i.Picture,
		&i.PreferredUsername,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SupervisorID,
	)
	return i, err
}

const getMemberByOrgAndEmail = `-- name: GetMemberByOrgAndEmail :one
SELECT id, org_id, role, email, email_verified, password_hash, name, given_name, family_name, picture, preferred_username, is_active, created_at, updated_at, supervisor_id FROM members_accounts
WHERE org_id = $1 AND email = $2 LIMIT 1
`

type GetMemberByOrgAndEmailParams struct {
	OrgID uuid.UUID `db:"org_id" json:"org_id"`
	Email string    `db:"email" json:"email"`
}

func (q *Queries) GetMemberByOrgAndEmail(ctx context.Context, arg GetMemberByOrgAndEmailParams) (MembersAccount, error) {
	row := q.db.QueryRowContext(ctx, getMemberByOrgAndEmail, arg.OrgID, arg.Email)
	var i MembersAccount
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Role,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Name,
		&i.GivenName,
		&i.FamilyName,
		&i.Picture,
		&i.PreferredUsername,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SupervisorID,
	)
	return i, err
}

const getMemberByOrgAndID = `-- name: GetMemberByOrgAndID :one
SELECT id, org_id, role, email, email_verified, password_hash, name, given_name, family_name, picture, preferred_username, is_active, created_at, updated_at, supervisor_id FROM members_accounts
WHERE org_id = $1 AND id = $2 LIMIT 1
`

type GetMemberByOrgAndIDParams struct {
	OrgID uuid.UUID `db:"org_id" json:"org_id"`
	ID    uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetMemberByOrgAndID(ctx context.Context, arg GetMemberByOrgAndIDParams) (MembersAccount, error) {
	row := q.db.QueryRowContext(ctx, getMemberByOrgAndID, arg.OrgID, arg.ID)
	var i MembersAccount
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Role,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Name,
		&i.GivenName,
		&i.FamilyName,
		&i.Picture,
		&i.PreferredUsername,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SupervisorID,
	)
	return i, err
}

const listMembersByOrg = `-- name: ListMembersByOrg :many
SELECT id, org_id, role, email, is_active, name, given_name, family_name, picture, preferred_username, supervisor_id, created_at
FROM members_accounts
WHERE org_id = $1
ORDER BY CASE role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END, created_at
`

type ListMembersByOrgRow struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	OrgID             uuid.UUID      `db:"org_id" json:"org_id"`
	Role              string         `db:"role" json:"role"`
	Email             string         `db:"email" json:"email"`
	IsActive          bool           `db:"is_active" json:"is_active"`
	Name              string         `db:"name" json:"name"`
	GivenName         sql.NullString `db:"given_name" json:"given_name"`
	FamilyName        sql.NullString `db:"family_name" json:"family_name"`
	Picture           sql.NullString `db:"picture" json:"picture"`
	PreferredUsername sql.NullString `db:"preferred_username" json:"preferred_username"`
	SupervisorID      uuid.NullUUID  `db:"supervisor_id" json:"supervisor_id"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
}

func (q *Queries) ListMembersByOrg(ctx context.Context, orgID uuid.UUID) ([]ListMembersByOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembersByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersByOrgRow{}
	for rows.Next() {
		var i ListMembersByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Role,
			&i.Email,
			&i.IsActive,
			&i.Name,
			&i.GivenName,
			&i.FamilyName,
			&i.Picture,
			&i.PreferredUsername,
			&i.SupervisorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsForMember = `-- name: ListMembershipsForMember :many
SELECT o.id, o.slug, o.name, o.rc_number, o.sector, o.allocated_seats, m.role,
    COALESCE((
		SELECT array_agg(e.entitlement ORDER BY e.entitlement)
		FROM org_entitlements e WHERE e.org_id = o.id
	), '{}')
FROM members_accounts m
JOIN organizations o ON o.id = m.org_id
WHERE m.id = $1 AND o.status = 'active'
ORDER BY o.created_at
`

type ListMembershipsForMemberRow struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	Slug           string      `db:"slug" json:"slug"`
	Name           string      `db:"name" json:"name"`
	RcNumber       string      `db:"rc_number" json:"rc_number"`
	Sector         string      `db:"sector" json:"sector"`
	AllocatedSeats int32       `db:"allocated_seats" json:"allocated_seats"`
	Role           string      `db:"role" json:"role"`
	Coalesce       interface{} `db:"coalesce" json:"coalesce"`
}

func (q *Queries) ListMembershipsForMember(ctx context.Context, id uuid.UUID) ([]ListMembershipsForMemberRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipsForMember, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsForMemberRow{}
	for rows.Next() {
		var i ListMembershipsForMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.RcNumber,
			&i.Sector,
			&i.AllocatedSeats,
			&i.Role,
			&i.Coalesce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM members_accounts WHERE org_id = $1 AND id = $2
`

type RemoveMemberParams struct {
	OrgID uuid.UUID `db:"org_id" json:"org_id"`
	ID    uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeMember, arg.OrgID, arg.ID)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE members_accounts SET role = $3, updated_at = NOW() WHERE org_id = $1 AND id = $2
`

type UpdateMemberRoleParams struct {
	OrgID uuid.UUID `db:"org_id" json:"org_id"`
	ID    uuid.UUID `db:"id" json:"id"`
	Role  string    `db:"role" json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberRole, arg.OrgID, arg.ID, arg.Role)
	return err
}

const updateMemberSupervisor = `-- name: UpdateMemberSupervisor :exec
UPDATE members_accounts SET supervisor_id = $3, updated_at = NOW() WHERE org_id = $1 AND id = $2
`

type UpdateMemberSupervisorParams struct {
	OrgID        uuid.UUID     `db:"org_id" json:"org_id"`
	ID           uuid.UUID     `db:"id" json:"id"`
	SupervisorID uuid.NullUUID `db:"supervisor_id" json:"supervisor_id"`
}

func (q *Queries) UpdateMemberSupervisor(ctx context.Context, arg UpdateMemberSupervisorParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberSupervisor, arg.OrgID, arg.ID, arg.SupervisorID)
	return err
}
