// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AdminSession struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Token     string    `db:"token" json:"token"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type AuditEvent struct {
	ID        uuid.UUID             `db:"id" json:"id"`
	UserID    uuid.NullUUID         `db:"user_id" json:"user_id"`
	OrgID     uuid.NullUUID         `db:"org_id" json:"org_id"`
	EventType string                `db:"event_type" json:"event_type"`
	Details   pqtype.NullRawMessage `db:"details" json:"details"`
	IpAddress pqtype.Inet           `db:"ip_address" json:"ip_address"`
	UserAgent sql.NullString        `db:"user_agent" json:"user_agent"`
	CreatedAt time.Time             `db:"created_at" json:"created_at"`
}

type AuthCode struct {
	ID                  uuid.UUID      `db:"id" json:"id"`
	Code                string         `db:"code" json:"code"`
	ClientID            string         `db:"client_id" json:"client_id"`
	SubjectType         string         `db:"subject_type" json:"subject_type"`
	SubjectID           uuid.UUID      `db:"subject_id" json:"subject_id"`
	RedirectUri         string         `db:"redirect_uri" json:"redirect_uri"`
	Scope               sql.NullString `db:"scope" json:"scope"`
	State               sql.NullString `db:"state" json:"state"`
	CodeChallenge       sql.NullString `db:"code_challenge" json:"code_challenge"`
	CodeChallengeMethod sql.NullString `db:"code_challenge_method" json:"code_challenge_method"`
	ExpiresAt           time.Time      `db:"expires_at" json:"expires_at"`
	Used                bool           `db:"used" json:"used"`
	CreatedAt           time.Time      `db:"created_at" json:"created_at"`
}

type EmailVerification struct {
	ID        uuid.UUID `db:"id" json:"id"`
	SubjectID uuid.UUID `db:"subject_id" json:"subject_id"`
	Token     string    `db:"token" json:"token"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	Used      bool      `db:"used" json:"used"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type MembersAccount struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	OrgID             uuid.UUID      `db:"org_id" json:"org_id"`
	Role              string         `db:"role" json:"role"`
	Email             string         `db:"email" json:"email"`
	EmailVerified     bool           `db:"email_verified" json:"email_verified"`
	PasswordHash      string         `db:"password_hash" json:"password_hash"`
	Name              string         `db:"name" json:"name"`
	GivenName         sql.NullString `db:"given_name" json:"given_name"`
	FamilyName        sql.NullString `db:"family_name" json:"family_name"`
	Picture           sql.NullString `db:"picture" json:"picture"`
	PreferredUsername sql.NullString `db:"preferred_username" json:"preferred_username"`
	IsActive          bool           `db:"is_active" json:"is_active"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time      `db:"updated_at" json:"updated_at"`
}

type OauthClient struct {
	ID            uuid.UUID `db:"id" json:"id"`
	ClientID      string    `db:"client_id" json:"client_id"`
	ClientSecret  string    `db:"client_secret" json:"client_secret"`
	BaseUrl       string    `db:"base_url" json:"base_url"`
	Name          string    `db:"name" json:"name"`
	RedirectUris  []string  `db:"redirect_uris" json:"redirect_uris"`
	GrantTypes    []string  `db:"grant_types" json:"grant_types"`
	ResponseTypes []string  `db:"response_types" json:"response_types"`
	IsActive      bool      `db:"is_active" json:"is_active"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time `db:"updated_at" json:"updated_at"`
}

type OrgEntitlement struct {
	ID          uuid.UUID `db:"id" json:"id"`
	OrgID       uuid.UUID `db:"org_id" json:"org_id"`
	Entitlement string    `db:"entitlement" json:"entitlement"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

type Organization struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	Name           string         `db:"name" json:"name"`
	Slug           string         `db:"slug" json:"slug"`
	LogoUrl        sql.NullString `db:"logo_url" json:"logo_url"`
	ProductID      uuid.UUID      `db:"product_id" json:"product_id"`
	ProductName    string         `db:"product_name" json:"product_name"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time      `db:"updated_at" json:"updated_at"`
	Status         string         `db:"status" json:"status"`
	RcNumber       sql.NullString `db:"rc_number" json:"rc_number"`
	Sector         sql.NullString `db:"sector" json:"sector"`
	AllocatedSeats int32          `db:"allocated_seats" json:"allocated_seats"`
}

type PasswordReset struct {
	ID        uuid.UUID `db:"id" json:"id"`
	SubjectID uuid.UUID `db:"subject_id" json:"subject_id"`
	Token     string    `db:"token" json:"token"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	Used      bool      `db:"used" json:"used"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type RefreshToken struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	Token       string         `db:"token" json:"token"`
	ClientID    string         `db:"client_id" json:"client_id"`
	SubjectType string         `db:"subject_type" json:"subject_type"`
	SubjectID   uuid.UUID      `db:"subject_id" json:"subject_id"`
	Scope       sql.NullString `db:"scope" json:"scope"`
	ExpiresAt   time.Time      `db:"expires_at" json:"expires_at"`
	Revoked     bool           `db:"revoked" json:"revoked"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
}

type User struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	Email             string         `db:"email" json:"email"`
	EmailVerified     bool           `db:"email_verified" json:"email_verified"`
	PasswordHash      string         `db:"password_hash" json:"password_hash"`
	Name              string         `db:"name" json:"name"`
	GivenName         sql.NullString `db:"given_name" json:"given_name"`
	FamilyName        sql.NullString `db:"family_name" json:"family_name"`
	Picture           sql.NullString `db:"picture" json:"picture"`
	PreferredUsername sql.NullString `db:"preferred_username" json:"preferred_username"`
	IsActive          bool           `db:"is_active" json:"is_active"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time      `db:"updated_at" json:"updated_at"`
	IsPlatformAdmin   bool           `db:"is_platform_admin" json:"is_platform_admin"`
}
