// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    name, slug, product_name, product_id, sector, allocated_seats
)
VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, name, slug, logo_url, product_id, product_name, sector, allocated_seats, rc_number, created_at, updated_at, status
`

type CreateOrganizationParams struct {
	Name           string    `db:"name" json:"name"`
	Slug           string    `db:"slug" json:"slug"`
	ProductName    string    `db:"product_name" json:"product_name"`
	ProductID      uuid.UUID `db:"product_id" json:"product_id"`
	Sector         string    `db:"sector" json:"sector"`
	AllocatedSeats int32     `db:"allocated_seats" json:"allocated_seats"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, createOrganization,
		arg.Name,
		arg.Slug,
		arg.ProductName,
		arg.ProductID,
		arg.Sector,
		arg.AllocatedSeats,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.ProductID,
		&i.ProductName,
		&i.Sector,
		&i.AllocatedSeats,
		&i.RcNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const dashboardStats = `-- name: DashboardStats :one
SELECT
  (SELECT COUNT(*) FROM organizations) AS organizations,
  (SELECT COUNT(*) FROM organizations WHERE status = 'active') AS active_orgs,
  (SELECT COUNT(*) FROM users) AS users,
  (SELECT COUNT(*) FROM oauth_clients) AS apps,
  (SELECT COUNT(*) FROM oauth_clients WHERE is_active) AS active_apps
`

type DashboardStatsRow struct {
	Organizations int64 `db:"organizations" json:"organizations"`
	ActiveOrgs    int64 `db:"active_orgs" json:"active_orgs"`
	Users         int64 `db:"users" json:"users"`
	Apps          int64 `db:"apps" json:"apps"`
	ActiveApps    int64 `db:"active_apps" json:"active_apps"`
}

func (q *Queries) DashboardStats(ctx context.Context) (DashboardStatsRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardStats)
	var i DashboardStatsRow
	err := row.Scan(
		&i.Organizations,
		&i.ActiveOrgs,
		&i.Users,
		&i.Apps,
		&i.ActiveApps,
	)
	return i, err
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, name, slug, logo_url, product_id, product_name, sector, allocated_seats, rc_number, created_at, updated_at, status FROM organizations 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrgByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrgByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.ProductID,
		&i.ProductName,
		&i.Sector,
		&i.AllocatedSeats,
		&i.RcNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const listOrgs = `-- name: ListOrgs :many
SELECT o.id, o.name, o.slug, o.status, o.product_id, o.sector, o.allocated_seats, o.product_name,
       o.rc_number, o.sector, o.allocated_seats, o.created_at, o.updated_at,
       (SELECT COUNT(*) FROM members_accounts m WHERE m.org_id = o.id) AS member_count
FROM organizations o
WHERE ($1 = '' OR o.name ILIKE $2 OR o.slug ILIKE $2)
ORDER BY o.created_at DESC
LIMIT $3
`

type ListOrgsParams struct {
	Column1 interface{} `db:"column_1" json:"column_1"`
	Name    string      `db:"name" json:"name"`
	Limit   int32       `db:"limit" json:"limit"`
}

type ListOrgsRow struct {
	ID               uuid.UUID `db:"id" json:"id"`
	Name             string    `db:"name" json:"name"`
	Slug             string    `db:"slug" json:"slug"`
	Status           string    `db:"status" json:"status"`
	ProductID        uuid.UUID `db:"product_id" json:"product_id"`
	Sector           string    `db:"sector" json:"sector"`
	AllocatedSeats   int32     `db:"allocated_seats" json:"allocated_seats"`
	ProductName      string    `db:"product_name" json:"product_name"`
	RcNumber         string    `db:"rc_number" json:"rc_number"`
	Sector_2         string    `db:"sector_2" json:"sector_2"`
	AllocatedSeats_2 int32     `db:"allocated_seats_2" json:"allocated_seats_2"`
	CreatedAt        time.Time `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time `db:"updated_at" json:"updated_at"`
	MemberCount      int64     `db:"member_count" json:"member_count"`
}

func (q *Queries) ListOrgs(ctx context.Context, arg ListOrgsParams) ([]ListOrgsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrgs, arg.Column1, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgsRow{}
	for rows.Next() {
		var i ListOrgsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.ProductID,
			&i.Sector,
			&i.AllocatedSeats,
			&i.ProductName,
			&i.RcNumber,
			&i.Sector_2,
			&i.AllocatedSeats_2,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrgStatus = `-- name: SetOrgStatus :exec
UPDATE organizations SET status = $2, updated_at = NOW() WHERE id = $1
`

type SetOrgStatusParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Status string    `db:"status" json:"status"`
}

func (q *Queries) SetOrgStatus(ctx context.Context, arg SetOrgStatusParams) error {
	_, err := q.db.ExecContext(ctx, setOrgStatus, arg.ID, arg.Status)
	return err
}
