// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPasswordReset = `-- name: CreatePasswordReset :exec
INSERT INTO password_resets (subject_id, token, expires_at)
VALUES ($1, $2, $3)
`

type CreatePasswordResetParams struct {
	SubjectID uuid.UUID `db:"subject_id" json:"subject_id"`
	Token     string    `db:"token" json:"token"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordReset, arg.SubjectID, arg.Token, arg.ExpiresAt)
	return err
}

const getPasswordReset = `-- name: GetPasswordReset :one
SELECT subject_id
FROM password_resets
WHERE token = $1 AND used = FALSE AND expires_at > NOW()
`

func (q *Queries) GetPasswordReset(ctx context.Context, token string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getPasswordReset, token)
	var subject_id uuid.UUID
	err := row.Scan(&subject_id)
	return subject_id, err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_resets SET used = TRUE WHERE token = $1
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetUsed, token)
	return err
}

const updateMemberPasswordHash = `-- name: UpdateMemberPasswordHash :exec
UPDATE members_accounts SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type UpdateMemberPasswordHashParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateMemberPasswordHash(ctx context.Context, arg UpdateMemberPasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberPasswordHash, arg.ID, arg.PasswordHash)
	return err
}
