// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: token.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (token, client_id, subject_type, subject_id, scope, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateRefreshTokenParams struct {
	Token       string         `db:"token" json:"token"`
	ClientID    string         `db:"client_id" json:"client_id"`
	SubjectType string         `db:"subject_type" json:"subject_type"`
	SubjectID   uuid.UUID      `db:"subject_id" json:"subject_id"`
	Scope       sql.NullString `db:"scope" json:"scope"`
	ExpiresAt   time.Time      `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.Token,
		arg.ClientID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Scope,
		arg.ExpiresAt,
	)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT client_id, subject_type, subject_id, scope
FROM refresh_tokens
WHERE token = $1 AND revoked = FALSE AND expires_at > NOW()
`

type GetRefreshTokenRow struct {
	ClientID    string         `db:"client_id" json:"client_id"`
	SubjectType string         `db:"subject_type" json:"subject_type"`
	SubjectID   uuid.UUID      `db:"subject_id" json:"subject_id"`
	Scope       sql.NullString `db:"scope" json:"scope"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, token)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.ClientID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Scope,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked = TRUE WHERE token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, token)
	return err
}
